version: "3.0"
services:
  api:
    image: "ditmar/api:${API_REST_VERSION}"
    ports:
      - "4000:4000"
    environment:
      - "PORT=4000"
      - "API_URL=https://pokeapi.co/api/v2/pokemon"
    restart: always