name: Deploy to aws EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      API_REST:
        description: "VERSION"
        required: true
        default: ""
      ENV:
        description: "ENVIRONMENT"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v2

      - name: Test SSH conection
        if: github.event_name == 'workflow_dispatch'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: echo "SSH connection successful"
